apiVersion: gitops.weave.works/v1alpha1
kind: GitopsCluster
metadata:
  labels:
    templates.weave.works/template-name: aws-eks-dev
    templates.weave.works/template-namespace: default
    weave.works/capi: bootstrap
  name: test
  namespace: default
  annotations:
    templates.weave.works/create-request: "{\"repository_url\":\"https://github.com/ww-gitops/paulc-mac\",\"head_branch\":\"edit-test-branch-41e748\",\"base_branch\":\"main\",\"title\":\"Edit test\",\"description\":\"This PR edits the resource test\",\"name\":\"aws-eks-dev\",\"parameter_values\":{\"AWS_REGION\":\"eu-west-1\",\"CLUSTER_NAME\":\"test\",\"KUBERNETES_VERSION\":\"v1.28\",\"WORKER_MACHINE_COUNT\":\"2\"},\"commit_message\":\"Edit test\",\"credentials\":{},\"namespace\":\"default\",\"template_kind\":\"GitOpsTemplate\"}"
    templates.weave.works/created-files: "{\"files\":[\"clusters/management/clusters/default/test.yaml\"]}"
spec:
  capiClusterRef:
    name: test

---
apiVersion: cluster.x-k8s.io/v1beta1
kind: Cluster
metadata:
  labels:
    templates.weave.works/template-name: aws-eks-dev
    templates.weave.works/template-namespace: default
  name: test
  namespace: default
spec:
  clusterNetwork:
    pods:
      cidrBlocks:
      - 10.120.0.0/20
  controlPlaneRef:
    apiVersion: controlplane.cluster.x-k8s.io/v1beta1
    kind: AWSManagedControlPlane
    name: test-control-plane
  infrastructureRef:
    apiVersion: controlplane.cluster.x-k8s.io/v1beta1
    kind: AWSManagedControlPlane
    name: test-control-plane

---
apiVersion: controlplane.cluster.x-k8s.io/v1beta1
kind: AWSManagedControlPlane
metadata:
  annotations:
    kustomize.toolkit.fluxcd.io/prune: disabled
    templates.weave.works/create-request: "{\"repository_url\":\"https://github.com/ww-gitops/paulc-mac\",\"head_branch\":\"edit-test-branch-41e748\",\"base_branch\":\"main\",\"title\":\"Edit test\",\"description\":\"This PR edits the resource test\",\"name\":\"aws-eks-dev\",\"parameter_values\":{\"AWS_REGION\":\"eu-west-1\",\"CLUSTER_NAME\":\"test\",\"KUBERNETES_VERSION\":\"v1.28\",\"WORKER_MACHINE_COUNT\":\"2\"},\"commit_message\":\"Edit test\",\"credentials\":{},\"namespace\":\"default\",\"template_kind\":\"GitOpsTemplate\"}"
    templates.weave.works/created-files: "{\"files\":[\"clusters/management/clusters/default/test.yaml\"]}"
  labels:
    templates.weave.works/template-name: aws-eks-dev
    templates.weave.works/template-namespace: default
  name: test-control-plane
  namespace: default
spec:
  additionalTags:
    creator: paul.carlton@weave.works
    customer: weaveworks-cx
    projectGid: 99999
  addons:
  - conflictResolution: overwrite
    name: vpc-cni
    version: v1.12.6-eksbuild.2
  eksClusterName: test
  region: eu-west-1
  sshKeyName: paulcarlton-ww
  version: v1.28

---
apiVersion: cluster.x-k8s.io/v1beta1
kind: MachinePool
metadata:
  annotations:
    kustomize.toolkit.fluxcd.io/prune: disabled
    templates.weave.works/create-request: "{\"repository_url\":\"https://github.com/ww-gitops/paulc-mac\",\"head_branch\":\"edit-test-branch-41e748\",\"base_branch\":\"main\",\"title\":\"Edit test\",\"description\":\"This PR edits the resource test\",\"name\":\"aws-eks-dev\",\"parameter_values\":{\"AWS_REGION\":\"eu-west-1\",\"CLUSTER_NAME\":\"test\",\"KUBERNETES_VERSION\":\"v1.28\",\"WORKER_MACHINE_COUNT\":\"2\"},\"commit_message\":\"Edit test\",\"credentials\":{},\"namespace\":\"default\",\"template_kind\":\"GitOpsTemplate\"}"
    templates.weave.works/created-files: "{\"files\":[\"clusters/management/clusters/default/test.yaml\"]}"
  labels:
    templates.weave.works/template-name: aws-eks-dev
    templates.weave.works/template-namespace: default
  name: test-pool-0
  namespace: default
spec:
  clusterName: test
  replicas: 2
  template:
    spec:
      bootstrap:
        dataSecretName: ""
      clusterName: test
      infrastructureRef:
        apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
        kind: AWSManagedMachinePool
        name: test-pool-0

---
apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: AWSManagedMachinePool
metadata:
  annotations:
    kustomize.toolkit.fluxcd.io/prune: disabled
    templates.weave.works/create-request: "{\"repository_url\":\"https://github.com/ww-gitops/paulc-mac\",\"head_branch\":\"edit-test-branch-41e748\",\"base_branch\":\"main\",\"title\":\"Edit test\",\"description\":\"This PR edits the resource test\",\"name\":\"aws-eks-dev\",\"parameter_values\":{\"AWS_REGION\":\"eu-west-1\",\"CLUSTER_NAME\":\"test\",\"KUBERNETES_VERSION\":\"v1.28\",\"WORKER_MACHINE_COUNT\":\"2\"},\"commit_message\":\"Edit test\",\"credentials\":{},\"namespace\":\"default\",\"template_kind\":\"GitOpsTemplate\"}"
    templates.weave.works/created-files: "{\"files\":[\"clusters/management/clusters/default/test.yaml\"]}"
  labels:
    templates.weave.works/template-name: aws-eks-dev
    templates.weave.works/template-namespace: default
  name: test-pool-0
  namespace: default
spec:
  remoteAccess:
    public: true
  scaling:
    maxSize: 3
    minSize: 1
  updateConfig:
    maxUnavailable: 1
